name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH Keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{secrets.EC2_SSH_KEY}}

      - name: Deploy to EC2
        run: |
          scp -r * ubuntu@54.204.68.65:/var/www/html
