name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install lftp and OpenSSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp openssh-client

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_ssh_key
          chmod 600 ec2_ssh_key

      - name: Deploy to FTP
        run: |
          lftp -e "set sftp:auto-confirm yes; mirror -R --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ -X .gitignore ./ /var/www/html; exit" -u ubuntu -p 22 sftp://ec2-44-204-61-43.compute-1.amazonaws.com
