name: Deploy to FTP

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install lftp and OpenSSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp openssh-client

      - name: Set up SSH agent
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2_ssh_key.ppk
          ssh-keygen -y -f ec2_ssh_key.ppk > ec2_ssh_key
          chmod 600 ec2_ssh_key
          eval $(ssh-agent -s)
          ssh-add ec2_ssh_key

      - name: Deploy to FTP
        run: |
          lftp -e "set sftp:auto-confirm yes; mirror -R --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ -X .gitignore ./ /var/www/html; exit" -u ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} -p 22 sftp://${{ secrets.HOST_DNS }}
