name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install lftp and OpenSSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp openssh-client

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_ssh_key
          chmod 600 ec2_ssh_key
      - name: Debug Secrets
        run: |
          echo "EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}"
          echo "USERNAME: ${{ secrets.USERNAME }}"
          echo "HOST_DNS: ${{ secrets.HOST_DNS }}"      